---
title: "values"
output: html_document
date: "2022-11-16"
---

```{r}
library(tidyverse)
library(dplyr)
library(Lock5Data)
```

``` {r}
HHH <- SleepStudy |> 
  filter(Happiness >= 28 & (ClassesMissed >= 1 & GPA >= 3.31 & DASScore >= 16) ) |>
  count()
#HHH = 13

LHH <- SleepStudy |> 
  filter(Happiness >= 28 & (ClassesMissed < 1 & GPA >= 3.31 & DASScore >= 16) ) |>
  count()
#LHH = 9

HLH <- SleepStudy |> 
  filter(Happiness >= 28 & (ClassesMissed >= 1 & GPA < 3.31 & DASScore >= 16) ) |>
  count()
#HLH = 17


LLH <- SleepStudy |> 
  filter(Happiness >= 28 & (ClassesMissed < 1 & GPA < 3.31 & DASScore >= 16) ) |>
  count()

#LLH = 4

HHL <- SleepStudy |> 
  filter(Happiness >= 28 & (ClassesMissed >= 1 & GPA >= 3.31 & DASScore < 16) ) |>
  count()
#HHL = 16

LHL <- SleepStudy |> 
  filter(Happiness >= 28 & (ClassesMissed < 1 & GPA >= 3.31 & DASScore < 16) ) |>
  count()

#LHL = 19

HLL <- SleepStudy |> 
  filter(Happiness >= 28 & (ClassesMissed >= 1 & GPA < 3.31 & DASScore < 16) ) |>
  count()

#HLL = 36

LLL <- SleepStudy |> 
  filter(Happiness >= 28 & (ClassesMissed < 1 & GPA < 3.31 & DASScore < 16) ) |>
  count()
#LLL = 16

```

``` {r}
L_HHH <- SleepStudy |> 
  filter(Happiness < 28 & (ClassesMissed >= 1 & GPA >= 3.31 & DASScore >= 16) ) |>
  count()
#L_HHH =20

L_LHH <- SleepStudy |> 
  filter(Happiness < 28 & (ClassesMissed < 1 & GPA >= 3.31 & DASScore >= 16) ) |>
  count()
#L_LHH = 14

L_HLH <- SleepStudy |> 
  filter(Happiness < 28 & (ClassesMissed >= 1 & GPA < 3.31 & DASScore >= 16) ) |>
  count()
#L_HLH = 35


L_LLH <- SleepStudy |> 
  filter(Happiness < 28 & (ClassesMissed < 1 & GPA < 3.31 & DASScore >= 16) ) |>
  count()

#L_LLH = 15

L_HHL <- SleepStudy |> 
  filter(Happiness < 28 & (ClassesMissed >= 1 & GPA >= 3.31 & DASScore < 16) ) |>
  count()
#L_HHL = 9

L_LHL <- SleepStudy |> 
  filter(Happiness < 28 & (ClassesMissed < 1 & GPA >= 3.31 & DASScore < 16) ) |>
  count()

#L_LHL = 8 

L_HLL <- SleepStudy |> 
  filter(Happiness < 28 & (ClassesMissed >= 1 & GPA < 3.31 & DASScore < 16) ) |>
  count()

#L_HLL = 13

L_LLL <- SleepStudy |> 
  filter(Happiness < 28 & (ClassesMissed < 1 & GPA < 3.31 & DASScore < 16) ) |>
  count()
#L_LLL = 9

```